export { ApiClientError } from "./client/errors";
export { getHealthStatus } from "./client/health";
export type { HealthClientOptions } from "./client/health";
export {
  archiveSchedule,
  createParticipantAvailability,
  createSchedule,
  getParticipantAvailability,
  getSchedule,
  lockSchedule,
  updateParticipantAvailability
} from "./client/schedules";
export type { ApiClientOptions } from "./client/schedules";
export {
  availabilityBlockSchema,
  availabilityResultsSchema,
  availabilitySlotInputSchema,
  archiveScheduleRequestSchema,
  archiveScheduleResponseSchema,
  apiErrorCodeSchema,
  apiErrorCodes,
  apiErrorResponseSchema,
  createParticipantAvailabilityRequestSchema,
  createParticipantAvailabilityResponseSchema,
  createScheduleRequestSchema,
  createScheduleResponseSchema,
  dailyWindowSchema,
  dateRangeSchema,
  getParticipantAvailabilityResponseSchema,
  getScheduleResponseSchema,
  healthStatusResponseSchema,
  lockScheduleRequestSchema,
  lockScheduleResponseSchema,
  participantAvailabilitySchema,
  participantSummarySchema,
  scheduleDetailSchema,
  scheduleStatusSummarySchema,
  scheduleSummarySchema,
  timeSlotAvailabilitySchema,
  timeSlotSchema,
  updateParticipantAvailabilityRequestSchema,
  updateParticipantAvailabilityResponseSchema
} from "./contracts";
export type {
  ArchiveScheduleRequest,
  ArchiveScheduleResponse,
  AvailabilityBlockDto,
  AvailabilityResults,
  AvailabilitySlotInput,
  ApiErrorCode,
  ApiErrorResponse,
  CreateParticipantAvailabilityRequest,
  CreateParticipantAvailabilityResponse,
  CreateScheduleRequest,
  CreateScheduleResponse,
  DailyWindowInput,
  DateRangeInput,
  GetParticipantAvailabilityResponse,
  GetScheduleResponse,
  HealthStatusResponse,
  LockScheduleRequest,
  LockScheduleResponse,
  ParticipantAvailability,
  ParticipantSummary,
  ScheduleDetail,
  ScheduleStatusSummary,
  ScheduleSummary,
  TimeSlotAvailabilityDto,
  TimeSlotDto,
  UpdateParticipantAvailabilityRequest,
  UpdateParticipantAvailabilityResponse
} from "./contracts";
